import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='flex gap-5 p-6 bg-slate-950 text-white'>
          <Link href="/blog">Blog</Link>
          <Link href="/contact-us">Contact Us</Link>
          <Link href="/dashboard">Dashboard</Link>
          <Link href="/dashboard/setting">Setting</Link>
          <Link href="/about">About</Link>
        </header>
        {children}</body>
    </html>
  )
}
